#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080

cd $OPENSHIFT_REPO_DIR
export GRADLE_USER_HOME=$OPENSHIFT_DATA_DIR/gradle
export GRADLE_HOME=$OPENSHIFT_DATA_DIR/gradle-1.6
export PATH=$GRADLE_HOME/bin:$PATH
export ENVIRONMENT=openshift

nohup gradle run &


## Non-gradle run command
# nohup java -jar target/drop.jar server helloworld.openshift.yml > ${OPENSHIFT_DIY_LOG_DIR}/helloworld.log 2>&1 &


